### ISSUE TITLE
Срывается синхронизация слоя 640x480 DIVGMX Ultimate (ep3ce144 c8n)

### ISSUE THREAD

**Issue by Caasper911** [mvvproject/DivGMX#1]
Выглядит так, как будто отсутствуют строчные импульсы, изображение за спектрумовскими экранами постоянно движется. При нажатии PrtScr - изображение стабилизируется, лишь раз в секунду замечаю подергивания

![img_20170425_090856](https://cloud.githubusercontent.com/assets/18189433/25372154/de5d732e-299c-11e7-925c-923ff5f4553d.jpg)

**Comment by mvvproject** [comment]
Сделал две сборки для ПЛИС [EP3C10E144C8N](https://github.com/mvvproject/DivGMX/raw/master/divgmx_nzx/divgmx_ep3_nzx_20170429.zip) и [EP4CE10E22C8N](https://github.com/mvvproject/DivGMX/raw/master/divgmx_nzx/divgmx_ep4_nzx_20170429.zip)
