### ISSUE TITLE
А вы думали, чтобы послать ваше устройство обзорщикам?

### ISSUE THREAD

**Issue by jan-kleks** [mvvproject/DivGMX#3]
Для рекламы. Например сюда:

[sinc LAIR](https://www.youtube.com/channel/UChC1Gcl-1bOkNPPzN_owcVg)

[The Spectrum Show (пример обзора)](https://youtu.be/7AgwFWEZXP4?t=203)

[GadgetUK164 - Retro Gaming Repairs & Mods (пример обзора)](https://www.youtube.com/watch?v=bGEeq1FM4JA&list=PLMjdUTC-GcRMqjM8_uBRYZkYzyJyCm8y5)

**Comment by mvvproject** [comment]
Спасибо, уже послал.
