### ISSUE TITLE
Missing TS-Config firmware for EP4CE10 based board

### ISSUE THREAD

**Issue by rl000** [mvvproject/DivGMX#4]
Hi,

I have DivGMX board on EP4CE10. But,  I am not able to restore ts-config firmware on my board because no jic file: https://github.com/mvvproject/DivGMX/tree/master/divgmx_tsconf (only for EP3C10)

Could you please advice?

Best regards,
Roman

**Comment by mvvproject** [comment]
TS-Conf (build 20180506) [
https://github.com/mvvproject/DivGMX/tree/master/divgmx_tsconf]
Wild Commander v0.98 [http://forum.tslabs.info/viewtopic.php?f=26&t=143]

SD-Card [
https://github.com/mvvproject/DivGMX/tree/master/divgmx_tsconf/softwares]

2018-05-06 12:37 GMT+03:00 Roman <notifications@github.com>:

**Comment by rl000** [comment]
Thank you!
